import lcddriver
import time
import sys

display = lcddriver.lcd()


display.lcd_display_string("Hola",1)
display.lcd_display_string("Ctrl+c -> salir",2)
time.sleep(1)
display.lcd_clear()
cont=0
try:
    while True:
        display.lcd_display_string("Hola mundo de", 1) 
        display.lcd_display_string("raspberry", 2) 
        time.sleep(2)                            
        display.lcd_clear()         
        display.lcd_display_string("Vamos a jugar ", 1)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Yo pregunto, ", 1)
        display.lcd_display_string("tu respondes ", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Teclea tu ", 1) 
        display.lcd_display_string("respuesta:D ", 2) 
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Pregunta 1:", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("que sigue? ", 1)
        display.lcd_display_string("luke, yo soy tu", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("a) padre", 1)
        display.lcd_display_string("b) hermano ", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Tienes 3 seg ", 1)
        display.lcd_display_string("para decidir... ", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("3", 1)
        time.sleep(1)
        display.lcd_display_string("2", 1)
        time.sleep(1)
        display.lcd_display_string("1", 1)
        time.sleep(1)
        display.lcd_display_string("Tiempo!", 1)
        a=input("a o b: ")
        if a == 'a':
                display.lcd_display_string("Correcto!",1)
                time.sleep(2)
                cont+=1
        else:
                display.lcd_display_string("Incorrecto!",1)
                display.lcd_display_string("es a)", 2)
                time.sleep(2)
                display.lcd_clear()
                display.lcd_display_string("es a)", 1)
                display.lcd_display_string("soy tu padre", 2)
                time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Teclea tu ", 1) 
        display.lcd_display_string("respuesta:D ", 2) 
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Pregunta 2:", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Frecuencia de ", 1)
        display.lcd_display_string("la4", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("a)440Hz c)220Hz", 1)
        display.lcd_display_string("b)880Hz", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Tienes 3 seg ", 1)
        display.lcd_display_string("para decidir... ", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("3", 1)
        time.sleep(1)
        display.lcd_display_string("2", 1)
        time.sleep(1)
        display.lcd_display_string("1", 1)
        time.sleep(1)
        display.lcd_clear()
        display.lcd_display_string("Tiempo!", 1)
        a= input("a, b o c: ")
        if a=='a':
                display.lcd_display_string("Correcto",1)
                time.sleep(2)
                cont+=1
        else:
                display.lcd_display_string("Incorrecto",1)
                display.lcd_display_string("es a)", 2)
                time.sleep(2)
                display.lcd_clear()
                display.lcd_display_string("es a)", 1)
                display.lcd_display_string("440Hz", 2)
                time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Teclea tu ", 1) 
        display.lcd_display_string("respuesta:D ", 2) 
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Pregunta 3:", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Piolin creyo ver", 1)
        display.lcd_display_string("un lindo...", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("a)romulano", 1)
        display.lcd_display_string("b)gatito", 2)
        time.sleep(2)
        display.lcd_display_string("Tienes 3 seg ", 1)
        display.lcd_display_string("para decidir... ", 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("3", 1)
        time.sleep(1)
        display.lcd_display_string("2", 1)
        time.sleep(1)
        display.lcd_display_string("1", 1)
        time.sleep(1)
        display.lcd_clear()
        display.lcd_display_string("Tiempo!", 1)
        a=input("a o b: ")
        if a=='b':
                display.lcd_clear()
                display.lcd_display_string("Correcto", 1)
                time.sleep(2)
                cont+=1
        else: 
                display.lcd_clear()
                display.lcd_display_string("Incorrecto", 1)
                display.lcd_display_string("es b)", 2)
                time.sleep(2)
                display.lcd_clear()
                display.lcd_display_string("es b)", 1)
                display.lcd_display_string("un lindo gatito", 2)
                time.sleep(2)
                
        
        display.lcd_display_string("Tu puntaje :D", 1)
        display.lcd_display_string(str(cont), 2)
        time.sleep(2)
        display.lcd_clear()
        display.lcd_display_string("Juego terminado", 1)
        display.lcd_display_string("Adios!", 2)
        time.sleep(2)
        break
    display.lcd_clear()
    display.lcd_backlight(0)
    sys.exit()

except KeyboardInterrupt: 
    display.lcd_clear()
    display.lcd_backlight(0)
